name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff
      - name: Print cwd and sys.path (debug)
        run: |
          pwd
          python - << 'PY'
          import sys, pprint
          pprint.pp(sys.path)
          PY
      - name: Run tests
        run: pytest -q
      - name: Ruff (E/F/I only)
        run: ruff --select I,E,F --ignore E501 .


